### ISSUE TITLE
Evaluation error when using download_acaps_npi_data()

### ISSUE THREAD

**Issue by conrad-mac** [trr266/tidycovid19#1]
Hi,

First of all, thanks for all your work in standing up this repository.

I am having an issue running `download_acaps_npi_data()` - I get the following error: `Error: Evaluation error: error -103 with zipfile in unzGetCurrentFileInfo`. I narrowed it down to 

```r
tmp_file <- tempfile(".xlsx")
utils::download.file(paste0("https://data.humdata.org", 
        dta_url), tmp_file, quiet = silent)
raw_dta <- readxl::read_excel(tmp_file, sheet = "Database")
```

The downloaded excel sheet is corrupted so won't open. I'm on Windows, so I think the issue is that the mode for `utils::download.file()` needs to be set to "wb" (this doesn't seem to be an issue for Unix-like OS - which I assume you're on). I.e.

```r
tmp_file <- tempfile(".xlsx")
utils::download.file(paste0("https://data.humdata.org", 
        dta_url), tmp_file, quiet = silent, mode = "wb")
raw_dta <- readxl::read_excel(tmp_file, sheet = "Database")
```

Kind regards

**Comment by joachim-gassen** [comment]
Thank you and great catch! You are right, download.file does not switch to binary on .xlsx files. I applied your fix. Can you check whether it works for you and then we can close the issue.

**Comment by conrad-mac** [comment]
No problem. I can confirm this is fixed.

**Comment by joachim-gassen** [comment]
Great. Thanks again!
