### ISSUE TITLE
Regional GCMR data

### ISSUE THREAD

**Issue by itamarcaspi** [trr266/tidycovid19#18]
Would it be possible to add regional/subregional data to the GCMR download function?

**Comment by joachim-gassen** [comment]
Apologies for the delay. While the merged data set remains at the country level, an update last week now allows the download of regional data where feasible. E.g.:

```
library(tidyverse)
library(tidycovid19)
df <- download_google_cmr_data(type = "country_region", cached = TRUE)

df %>% filter(iso3c == "DEU") %>%
  ggplot(aes(x = date, y = retail_recreation, color = region)) +
  geom_line()
```

Does that work for you?

**Comment by itamarcaspi** [comment]
It works. Thanks!

**Comment by joachim-gassen** [comment]
Perfect. Then let's consider this issue closed.
