### ISSUE TITLE
Outdated data?

### ISSUE THREAD

**Issue by alexandrsanches** [trr266/tidycovid19#28]
Hey, 

I was using your package to create some charts and I noticed that the data date is out of date. The last available data is from June sixth. 

![Captura de Tela 2020-06-09 às 11 40 55](https://user-images.githubusercontent.com/55547524/84161858-1c73b880-aa46-11ea-96d3-96dd06cb1c47.png)

Is something wrong downloading the data from your sources?

Thank you.

**Comment by joachim-gassen** [comment]
Apologies, I did not get around to update the data yesterday and sometimes the data is lagging a day. I just uploaded the new update so things should be current again. Remember that you can always download current data from the original source by using `cached = FALSE`. Thanks!

**Comment by alexandrsanches** [comment]
Trying ```download_merged_data(cached = FALSE)``` it returns the following error:

![Captura de Tela 2020-06-09 às 14 57 41](https://user-images.githubusercontent.com/55547524/84182958-98c7c500-aa61-11ea-89ee-96a0f24ddc66.png)

My ```packageDescription```:

```
Package: tidycovid19
Type: Package
Title: Download, Tidy and Visualize Covid-19 Related Data
Version: 0.0.0.9000
Authors@R: person("Joachim", "Gassen", role = c("aut", "cre"), email = "gassen@wiwi.hu-berlin.de", comment =
            c(ORCID = "0000-0003-4364-2911"))
Description: This package facilitates the download of current Covid-19 related data from various sources,
            including the Johns Hopkins University CSSE team, the Assessment Capacities Project (ACAPS), Google
            Trends and movement data, Government measures provided by University of Oxford and additional
            country-level data provided by the World Bank. These data can be downloaded separately or in one
            merged data frame. In addition, the package features a function and shiny app to visualize the
            country-level spread of Covid-19.
Depends: R (>= 2.10)
License: MIT + file LICENSE
Imports: xml2, rvest, readxl, magrittr, dplyr, tidyr, countrycode, ggplot2, wbstats, gghighlight, gtrendsR,
            ggrepel, readr, rlang, scales, lubridate, shiny, shinyWidgets, shinyjs, rclipboard, stringr, zoo,
            gganimate, maps
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.0
RemoteType: github
RemoteHost: api.github.com
RemoteRepo: tidycovid19
RemoteUsername: joachim-gassen
RemoteRef: master
RemoteSha: 0e494b8feabdaf3e129e613e24e3ff815ccab04c
GithubRepo: tidycovid19
GithubUsername: joachim-gassen
GithubRef: master
GithubSHA1: 0e494b8feabdaf3e129e613e24e3ff815ccab04c
NeedsCompilation: no
Packaged: 2020-05-27 02:58:14 UTC; alexandre
Author: Joachim Gassen [aut, cre] (<https://orcid.org/0000-0003-4364-2911>)
Maintainer: Joachim Gassen <gassen@wiwi.hu-berlin.de>
Built: R 4.0.0; ; 2020-05-27 02:58:15 UTC; unix

```

**Comment by joachim-gassen** [comment]
The install is dated. But it seems that you have problems resolving https://covid.ourworldindata.org. This seems to be a local problem. The warnings are fine. Can you check whether you can reach the link and if you can update the package and retry? Cheers!

**Comment by alexandrsanches** [comment]
Hi! I reinstalled the package and the issue keep going. But seems to be a different error.

![Captura de Tela 2020-06-09 às 19 44 52](https://user-images.githubusercontent.com/55547524/84208287-c58fd280-aa89-11ea-953f-1f9941606d76.png)

**Comment by joachim-gassen** [comment]
Thanks! This seems to the same issue as discussed here: #27.  It is an issue in {gtrendsr} that you can circumvent by installing my local fork of the {gtrendsr} package until the issue is addressed in the main branch of {gtrendsr}. Feel free to post to #27 if you have additional questions. Closing this issue now.

**Comment by alexandrsanches** [comment]
Thanks, I will continue to update with ```cached = TRUE``` for now. Keep going with the excellent work!
