### ISSUE TITLE
install_github("joachim-gassen/tidycovid19") does not work (dependency 'wbstats' is not available)

### ISSUE THREAD

**Issue by rmartischang** [trr266/tidycovid19#31]
Dear all, 

I recently re-tried to install tidycovid on R v4.0 from the function install_github. 
Everything worked perfectly except for the dependency : wbstats. 
I received the error message : 

Installing package into ‘C:/Users/usr/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
ERROR: dependency 'wbstats' is not available for package 'tidycovid19'
* removing 'C:/Users/usr/Documents/R/win-library/4.0/tidycovid19'

When checking on CRAN, I just saw that the package has been removed : 
https://cran.r-project.org/web/packages/wbstats/index.html

Would you know how to handle this issue ? 

Kind regards,

**Comment by joachim-gassen** [comment]
Hi there!

Thanks for bringing this up. It seems as if `wbstats` was (temporarily) removed from CRAN most likely as it failed to cleanly pass `CMD CHECK` on too many platforms. While I am confident that the maintainer of the package will address this issue soon, you might want to see whether installing the Github version (https://github.com/nset-ornl/wbstats) via `remotes::install_github('nset-ornl/wbstats')` prior to installing `tidycovid19` works for you.

Thanks for letting us know whether this works for you,

Joachim

**Comment by rmartischang** [comment]
Dear Joachim, 

I installed wbstats with the code you indicated and "tidycovid19" works now perfectly, 

Many thanks for your help

**Comment by joachim-gassen** [comment]
Glad that it helped. I will leave this issue open for a while until the underlying issue in `wbstats` is fixed.

**Comment by joachim-gassen** [comment]
Closing this now as `wbstats` is back on CRAN.
