### ISSUE TITLE
install_github() does not work. tarball not found

### ISSUE THREAD

**Issue by jameshunterbr** [trr266/tidycovid19#34]
Cannot seem to download the package as remotes::install_github("joachim-gassen/tidycovid19") does not find the tarball

**Comment by joachim-gassen** [comment]
Hi there:

Sorry but I cannot reproduce that. Could you please verify that it is was not caused by a temporary network glitch and if you continue to encounter that issue post the complete error message together with the output of `devtools::session_info()`?

Thanks!

**Comment by jameshunterbr** [comment]
I've tried it again with both remotes and devtools. Here is the output and the sessionInfo.

> remotes::install_github("joachim-gassen/tidycovid19")
Downloading GitHub repo joachim-gassen/tidycovid19@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/joachim-gassen/tidycovid19/tarball/HEAD' failed
> devtools::install_github("joachim-gassen/tidycovid19")
Downloading GitHub repo joachim-gassen/tidycovid19@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/joachim-gassen/tidycovid19/tarball/HEAD' failed

> devtools::session_info()
- Session info ---------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Sao_Paulo           
 date     2020-11-25                  

- Packages -------------------------------------------------------------------------------------------------------------
 package       * version date       lib source        
 abind           1.4-5   2016-07-21 [1] CRAN (R 4.0.0)
 assertthat      0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
 backports       1.2.0   2020-11-02 [1] CRAN (R 4.0.3)
 base64enc       0.1-3   2015-07-28 [1] CRAN (R 4.0.0)
 broom           0.7.2   2020-10-20 [1] CRAN (R 4.0.3)
 callr           3.5.1   2020-10-13 [1] CRAN (R 4.0.3)
 car             3.0-10  2020-09-29 [1] CRAN (R 4.0.2)
 carData         3.0-4   2020-05-22 [1] CRAN (R 4.0.0)
 cellranger      1.1.0   2016-07-27 [1] CRAN (R 4.0.0)
 checkmate       2.0.0   2020-02-06 [1] CRAN (R 4.0.0)
 cli             2.2.0   2020-11-20 [1] CRAN (R 4.0.3)
 cluster         2.1.0   2019-06-19 [1] CRAN (R 4.0.3)
 codetools       0.2-16  2018-12-24 [2] CRAN (R 4.0.3)
 colorspace      2.0-0   2020-11-11 [1] CRAN (R 4.0.3)
 crayon          1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
 curl            4.3     2019-12-02 [1] CRAN (R 4.0.0)
 data.table      1.13.2  2020-10-19 [1] CRAN (R 4.0.3)
 DBI             1.1.0   2019-12-15 [1] CRAN (R 4.0.0)
 dbplyr          2.0.0   2020-11-03 [1] CRAN (R 4.0.3)
 dendextend      1.14.0  2020-08-26 [1] CRAN (R 4.0.2)
 desc            1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
 devtools        2.3.2   2020-09-18 [1] CRAN (R 4.0.2)
 digest          0.6.27  2020-10-24 [1] CRAN (R 4.0.3)
 distill         1.0     2020-10-22 [1] CRAN (R 4.0.3)
 downlit         0.2.1   2020-11-04 [1] CRAN (R 4.0.3)
 dplyr         * 1.0.2   2020-08-18 [1] CRAN (R 4.0.2)
 ellipsis        0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
 evaluate        0.14    2019-05-28 [1] CRAN (R 4.0.0)
 factoextra    * 1.0.7   2020-04-01 [1] CRAN (R 4.0.3)
 FactoMineR    * 2.3     2020-02-29 [1] CRAN (R 4.0.3)
 fansi           0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
 farver          2.0.3   2020-01-16 [1] CRAN (R 4.0.0)
 flashClust      1.01-2  2012-08-21 [1] CRAN (R 4.0.3)
 forcats       * 0.5.0   2020-03-01 [1] CRAN (R 4.0.0)
 foreach         1.5.1   2020-10-15 [1] CRAN (R 4.0.3)
 foreign         0.8-80  2020-05-24 [2] CRAN (R 4.0.3)
 fs              1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
 generics        0.1.0   2020-10-31 [1] CRAN (R 4.0.3)
 ggplot2       * 3.3.2   2020-06-19 [1] CRAN (R 4.0.0)
 ggpubr          0.4.0   2020-06-27 [1] CRAN (R 4.0.2)
 ggrepel         0.8.2   2020-03-08 [1] CRAN (R 4.0.0)
 ggsci           2.9     2018-05-14 [1] CRAN (R 4.0.0)
 ggsignif        0.6.0   2019-08-08 [1] CRAN (R 4.0.0)
 glue          * 1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
 gridExtra       2.3     2017-09-09 [1] CRAN (R 4.0.0)
 gtable          0.3.0   2019-03-25 [1] CRAN (R 4.0.0)
 haven           2.3.1   2020-06-01 [1] CRAN (R 4.0.0)
 heatmaply     * 1.1.1   2020-08-25 [1] CRAN (R 4.0.3)
 here          * 1.0.0   2020-11-15 [1] CRAN (R 4.0.3)
 highr           0.8     2019-03-20 [1] CRAN (R 4.0.0)
 hms             0.5.3   2020-01-08 [1] CRAN (R 4.0.0)
 htmltools       0.5.0   2020-06-16 [1] CRAN (R 4.0.0)
 htmlwidgets     1.5.2   2020-10-03 [1] CRAN (R 4.0.2)
 httr            1.4.2   2020-07-20 [1] CRAN (R 4.0.2)
 iterators       1.0.13  2020-10-15 [1] CRAN (R 4.0.3)
 janitor       * 2.0.1   2020-04-12 [1] CRAN (R 4.0.0)
 jsonlite        1.7.1   2020-09-07 [1] CRAN (R 4.0.2)
 knitr           1.30    2020-09-22 [1] CRAN (R 4.0.2)
 labeling        0.4.2   2020-10-20 [1] CRAN (R 4.0.3)
 lattice         0.20-41 2020-04-02 [2] CRAN (R 4.0.3)
 lazyeval        0.2.2   2019-03-15 [1] CRAN (R 4.0.0)
 leaps           3.1     2020-01-16 [1] CRAN (R 4.0.3)
 lifecycle       0.2.0   2020-03-06 [1] CRAN (R 4.0.0)
 lubridate       1.7.9.2 2020-11-13 [1] CRAN (R 4.0.3)
 magick          2.5.2   2020-11-10 [1] CRAN (R 4.0.3)
 magrittr        2.0.1   2020-11-17 [1] CRAN (R 4.0.3)
 MASS            7.3-53  2020-09-09 [1] CRAN (R 4.0.2)
 Matrix          1.2-18  2019-11-27 [2] CRAN (R 4.0.3)
 matrixStats     0.57.0  2020-09-25 [1] CRAN (R 4.0.2)
 memoise         1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
 modelr          0.1.8   2020-05-19 [1] CRAN (R 4.0.0)
 munsell         0.5.0   2018-06-12 [1] CRAN (R 4.0.0)
 openxlsx        4.2.3   2020-10-27 [1] CRAN (R 4.0.3)
 pacman          0.5.1   2019-03-11 [1] CRAN (R 4.0.0)
 pander          0.6.3   2018-11-06 [1] CRAN (R 4.0.0)
 pillar          1.4.7   2020-11-20 [1] CRAN (R 4.0.3)
 pkgbuild        1.1.0   2020-07-13 [1] CRAN (R 4.0.2)
 pkgconfig       2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
 pkgload         1.1.0   2020-05-29 [1] CRAN (R 4.0.0)
 plotly        * 4.9.2.1 2020-04-04 [1] CRAN (R 4.0.0)
 plyr            1.8.6   2020-03-03 [1] CRAN (R 4.0.0)
 prettyunits     1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
 processx        3.4.4   2020-09-03 [1] CRAN (R 4.0.2)
 pryr            0.1.4   2018-02-18 [1] CRAN (R 4.0.0)
 ps              1.4.0   2020-10-07 [1] CRAN (R 4.0.2)
 purrr         * 0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
 R6              2.5.0   2020-10-28 [1] CRAN (R 4.0.3)
 rapportools     1.0     2014-01-07 [1] CRAN (R 4.0.0)
 RColorBrewer    1.1-2   2014-12-07 [1] CRAN (R 4.0.0)
 Rcpp            1.0.5   2020-07-06 [1] CRAN (R 4.0.2)
 readr         * 1.4.0   2020-10-05 [1] CRAN (R 4.0.2)
 readxl        * 1.3.1   2019-03-13 [1] CRAN (R 4.0.0)
 registry        0.5-1   2019-03-05 [1] CRAN (R 4.0.0)
 remotes         2.2.0   2020-07-21 [1] CRAN (R 4.0.2)
 reprex          0.3.0   2019-05-16 [1] CRAN (R 4.0.0)
 reshape2        1.4.4   2020-04-09 [1] CRAN (R 4.0.0)
 rio             0.5.16  2018-11-26 [1] CRAN (R 4.0.0)
 rlang           0.4.8   2020-10-08 [1] CRAN (R 4.0.2)
 rmarkdown       2.5     2020-10-21 [1] CRAN (R 4.0.3)
 rprojroot       2.0.2   2020-11-15 [1] CRAN (R 4.0.3)
 rsconnect       0.8.16  2019-12-13 [1] CRAN (R 4.0.0)
 rstatix         0.6.0   2020-06-18 [1] CRAN (R 4.0.0)
 rstudioapi      0.13    2020-11-12 [1] CRAN (R 4.0.3)
 rvest           0.3.6   2020-07-25 [1] CRAN (R 4.0.2)
 scales          1.1.1   2020-05-11 [1] CRAN (R 4.0.0)
 scatterplot3d   0.3-41  2018-03-14 [1] CRAN (R 4.0.3)
 seriation       1.2-9   2020-10-01 [1] CRAN (R 4.0.2)
 sessioninfo     1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
 snakecase       0.11.0  2019-05-25 [1] CRAN (R 4.0.0)
 stringi         1.5.3   2020-09-09 [1] CRAN (R 4.0.2)
 stringr       * 1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
 summarytools  * 0.9.6   2020-03-02 [1] CRAN (R 4.0.0)
 testthat        3.0.0   2020-10-31 [1] CRAN (R 4.0.3)
 tibble        * 3.0.4   2020-10-12 [1] CRAN (R 4.0.2)
 tidyr         * 1.1.2   2020-08-27 [1] CRAN (R 4.0.2)
 tidyselect      1.1.0   2020-05-11 [1] CRAN (R 4.0.0)
 tidyverse     * 1.3.0   2019-11-21 [1] CRAN (R 4.0.0)
 TSP             1.1-10  2020-04-17 [1] CRAN (R 4.0.0)
 usethis         1.6.3   2020-09-17 [1] CRAN (R 4.0.2)
 utf8            1.1.4   2018-05-24 [1] CRAN (R 4.0.0)
 vctrs           0.3.5   2020-11-17 [1] CRAN (R 4.0.3)
 viridis       * 0.5.1   2018-03-29 [1] CRAN (R 4.0.0)
 viridisLite   * 0.3.0   2018-02-01 [1] CRAN (R 4.0.0)
 webshot         0.5.2   2019-11-22 [1] CRAN (R 4.0.0)
 withr           2.3.0   2020-09-22 [1] CRAN (R 4.0.2)
 xfun            0.19    2020-10-30 [1] CRAN (R 4.0.3)
 xml2            1.3.2   2020-04-23 [1] CRAN (R 4.0.0)
 yaml            2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
 zip             2.1.1   2020-08-27 [1] CRAN (R 4.0.2)

[1] C:/Users/james/OneDrive/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.3/library

**Comment by joachim-gassen** [comment]
Thank you! While I still cannot reproduce this issue, I have two suggestions. 

1. Can you check whether the following works for you:
```
options()$download.file.method
tfile <- tempfile()
file <- utils::download.file('https://api.github.com/repos/joachim-gassen/tidycovid19/tarball/HEAD', tfile)
```
Based on the above, it should not. I wonder whether this might be related to your file download method (this is why I included the options call above). You could play around with the method options that are available for your OS. See here for people having similar issues: https://github.com/r-lib/remotes/issues/130. 

2. The obvious question: Do you face similar problems with other Github repos? If not and the above is inconclusive then I can only speculate that the relative large file size (41.7 MB) plays a role.

**Comment by jameshunterbr** [comment]
Last question first: no, this is the first time I have encountered this with a GitHub repo package. I have downloaded many before.

This is the output I get from your test code:

```
> options()$download.file.method
NULL
> tfile <- tempfile()
> file <- utils::download.file('https://api.github.com/repos/joachim-gassen/tidycovid19/tarball/HEAD', tfile)
trying URL 'https://api.github.com/repos/joachim-gassen/tidycovid19/tarball/HEAD'
Content type 'application/x-gzip' length unknown
downloaded 41.8 MB

> tfile
[1] "C:\\Users\\james\\AppData\\Local\\Temp\\RtmpisYPWN\\file110436b01ac8"
> 
```
There is a file in the directory indicated in tfile that is 41.7 MB.

So, something happened. What, I'm not sure.

**Comment by joachim-gassen** [comment]
So the download works. What confuses me is that your method for downloading files is set to NULL. Normally, on windows, it defaults to:

```
> options()$download.file.method
[1] "wininet"
```

However, the install_github code sets the download method to "auto" if the option is set to NULL and this also works in my Windows environment. The last hint that I can give you is to explicitly change the method to "wininet" prior to calling install_github to see whether this helps.

```
options(download.file.method = "wininet")
remotes::install_github("joachim-gassen/tidycovid19")
```

Good luck and thanks for letting me (and potential others) know whether it works.

**Comment by jameshunterbr** [comment]
That was it, Joachim. changing the options to "wininet" made the download successful. Many thanks for the help.
