### ISSUE TITLE
Include testing data from worldometer

### ISSUE THREAD

**Issue by jorgesat** [trr266/tidycovid19#4]
Might be good idea to scrape data from https://www.worldometers.info/coronavirus/
which includes some interesting data like "Total Tests".

**Comment by joachim-gassen** [comment]
Hi there and apologies for leaving this linger here for so long. This certainly is a good suggestion. My problem with worldometers is that I want to limit the package to authoritative data sources, meaning to datasources that are collecting the data and taking responsibility for its quality. The data from the Johns Hopkins University CSSE team is sort of an exemption as they have become one of the de facto standards for measuring the spread of the pandemic.

Data on testing would be good to include, though. The only transnational source I am aware of would be "Our World in Data" (https://github.com/owid/covid-19-data/tree/master/public/data). Still an exemption from my self-imposed rule but at least they provide a decent time series and commit publicly for maintaining this data going forward.

What do you think?

**Comment by joachim-gassen** [comment]
Quick follow up: My commit of today includes testing data from Our World in Data. See whether this works for you.
