### ISSUE TITLE
great blogger

### ISSUE THREAD

**Issue by yurisong1** [trr266/tidycovid19#6]
I have seen a blog using tidycovid19 package of yours, it gives great depth of data and collectively collecting some interesting aspect. Can I confirm that in tidycovid19, there is a function named extract_line_graph_bitmaps? I see it from the example from https://www.r-bloggers.com/scraping-google-covid-19-community-movement-data-from-pdf-figures/. However, I could not call or find script from the github repo.

**Comment by joachim-gassen** [comment]
Hi there and thanks. The function is not exported (hence the `:::` in its reference) but can still be assessed. It is located in `R/scrape_google_cmr_data.R`. Please keep in mind that this is an internal function that will _only_ work on the Community Movement Report's PDF files as they are currently distributed by Google.
