### ISSUE TITLE
Feature request: Apple Mobility Trends Reports

### ISSUE THREAD

**Issue by itamarcaspi** [trr266/tidycovid19#8]
Hi,
Fantastic work! I use your package frequently for policy work. Thanks!

And for the issue: would it be possible to add Appl's Mobility Trends Report to the package?

[https://www.apple.com/covid19/mobility](https://www.apple.com/covid19/mobility)

Thank you for considering,
Itamar

**Comment by yohananouaknine** [comment]
Hi Joachim,
Thank u for adding Google mobility and Google Trends. For some reason, I don't see the data of Israel in the google trends data. Any idea what might be the cause.

Thanks again.
Yohanan

**Comment by itamarcaspi** [comment]
I just saw that you added apple MPT. Great!

You can close this issue.

**Comment by joachim-gassen** [comment]
> Hi,
> Fantastic work! I use your package frequently for policy work. Thanks!
> 
> And for the issue: would it be possible to add Appl's Mobility Trends Report to the package?
> 
> https://www.apple.com/covid19/mobility
> 
> Thank you for considering,
> Itamar

Can you update your package install? I have added apple MTR data today. It should also be included in the merged dataset. Thanks for letting me know whether it works for you. Cheers, Joachim

**Comment by itamarcaspi** [comment]
It works!

Thanks
